org: tenantutec123
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::730335337301:role/LabRole

functions:
  scraping_lambda:
    handler: scraping_lambda.lambda_handler  # Asegúrate de que el nombre del archivo y la función coincidan
    package:
      include:
        - ./**  # Incluye todo el contenido del directorio
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaScrapingDynamoDBNueva:  # Nombre único para la nueva tabla
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaScrapingDynamoDBNueva  # Nombre específico para evitar colisiones
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
